# This file was generated by GoReleaser. DO NOT EDIT.
cask "kintoun-ssm-tunnel" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "525aed84702b92e9c82eaeef7367f0f2eaf6ecaa19762d16bf1b0191f11d429a"
      url "https://github.com/kintoun-secops/kintoun-ssm-tunnel/releases/download/v#{version}/kintoun-ssm-tunnel_v#{version}_darwin_arm64.tar.gz"
      rename "kintoun-ssm-tunnel_v0.1.1_darwin_arm64/kintoun-ssm-tunnel", "kintoun-ssm-tunnel"
    end
    on_intel do
      sha256 "482acce5f4ae886997e1cd2d9635a7e880172cd3eaa1321ba279988f0f41db27"
      url "https://github.com/kintoun-secops/kintoun-ssm-tunnel/releases/download/v#{version}/kintoun-ssm-tunnel_v#{version}_darwin_amd64.tar.gz"
      rename "kintoun-ssm-tunnel_v0.1.1_darwin_amd64/kintoun-ssm-tunnel", "kintoun-ssm-tunnel"
    end
  end
  on_linux do
    on_arm do
      sha256 "35d4c1f39d13d6dbebd3c528545540b176fc09da65f6298d48830fa4bd481780"
      url "https://github.com/kintoun-secops/kintoun-ssm-tunnel/releases/download/v#{version}/kintoun-ssm-tunnel_v#{version}_linux_arm64.tar.gz"
      rename "kintoun-ssm-tunnel_v0.1.1_linux_arm64/kintoun-ssm-tunnel", "kintoun-ssm-tunnel"
    end
    on_intel do
      sha256 "1f2a1dd55ccbdf173b1e18f5464799b1eb25f9c0e6bfa9feb8dfcf621b955f6a"
      url "https://github.com/kintoun-secops/kintoun-ssm-tunnel/releases/download/v#{version}/kintoun-ssm-tunnel_v#{version}_linux_amd64.tar.gz"
      rename "kintoun-ssm-tunnel_v0.1.1_linux_amd64/kintoun-ssm-tunnel", "kintoun-ssm-tunnel"
    end
  end

  name "kintoun-ssm-tunnel"
  desc ""
  homepage "https://github.com/kintoun-secops/kintoun-ssm-tunnel"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kintoun-ssm-tunnel"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kintoun-ssm-tunnel"]
    end
  end

  # No zap stanza required
end
