# This file was generated by GoReleaser. DO NOT EDIT.
cask "ktun" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "9293db048f46a5218c4fd87ee04b21cfdcd0b28b4558fdf0ae3af53092061950"
      url "https://github.com/kintoun-secops/kintoun-ssm-tunnel/releases/download/v#{version}/ktun_v#{version}_darwin_arm64.tar.gz"
      rename "ktun_v0.2.0_darwin_arm64/ktun", "ktun"
    end
    on_intel do
      sha256 "ca9c7351a37cd204715bc152e493fc910351d5b5325dc3a50f343b9bbebafe63"
      url "https://github.com/kintoun-secops/kintoun-ssm-tunnel/releases/download/v#{version}/ktun_v#{version}_darwin_amd64.tar.gz"
      rename "ktun_v0.2.0_darwin_amd64/ktun", "ktun"
    end
  end
  on_linux do
    on_arm do
      sha256 "8eb9c22ce831286375fc5c4588340a4d7177b8b12aadb02f42dbbcbbdd88eb8f"
      url "https://github.com/kintoun-secops/kintoun-ssm-tunnel/releases/download/v#{version}/ktun_v#{version}_linux_arm64.tar.gz"
      rename "ktun_v0.2.0_linux_arm64/ktun", "ktun"
    end
    on_intel do
      sha256 "46bd372a515a3a56ba69472485036c3ff9ac60ce00fdfdc017ceacd70ab7d63d"
      url "https://github.com/kintoun-secops/kintoun-ssm-tunnel/releases/download/v#{version}/ktun_v#{version}_linux_amd64.tar.gz"
      rename "ktun_v0.2.0_linux_amd64/ktun", "ktun"
    end
  end

  name "ktun"
  desc ""
  homepage "https://github.com/kintoun-secops/kintoun-ssm-tunnel"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ktun"

  # No zap stanza required
end
