# This file was generated by GoReleaser. DO NOT EDIT.
cask "ktun" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "4f94c7a8725ad48b201a82641b8f3238e3764f0dd7703699b84be70ded8ab6e6"
      url "https://github.com/kintoun-secops/kintoun-ssm-tunnel/releases/download/v#{version}/ktun_v#{version}_darwin_arm64.tar.gz"
      rename "ktun_v0.3.0_darwin_arm64/ktun", "ktun"
    end
    on_intel do
      sha256 "6c99c22c570e8a8632f14699157665178a04457b45ded2a4d0fe034b1afda3f0"
      url "https://github.com/kintoun-secops/kintoun-ssm-tunnel/releases/download/v#{version}/ktun_v#{version}_darwin_amd64.tar.gz"
      rename "ktun_v0.3.0_darwin_amd64/ktun", "ktun"
    end
  end
  on_linux do
    on_arm do
      sha256 "84dc826381b4080154ac27ef6b5dfb866cc3bf4a221fa147a44b9778c53c6b6a"
      url "https://github.com/kintoun-secops/kintoun-ssm-tunnel/releases/download/v#{version}/ktun_v#{version}_linux_arm64.tar.gz"
      rename "ktun_v0.3.0_linux_arm64/ktun", "ktun"
    end
    on_intel do
      sha256 "39e2f08bcd73507e37c53fbeff85701830ef1e8ca62d12313507d863ee4c8980"
      url "https://github.com/kintoun-secops/kintoun-ssm-tunnel/releases/download/v#{version}/ktun_v#{version}_linux_amd64.tar.gz"
      rename "ktun_v0.3.0_linux_amd64/ktun", "ktun"
    end
  end

  name "ktun"
  desc ""
  homepage "https://github.com/kintoun-secops/kintoun-ssm-tunnel"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ktun"

  # No zap stanza required
end
